name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Emscripten toolchain
        uses: mymindstorm/setup-emsdk@v11
      - name: Compile
        run: emmake make
      - name: NPM Publish
        uses: JS-DevTools/npm-publish@0f451a94170d1699fd50710966d48fb26194d939
        with:
          token: ${{ secrets.NPM_TOKEN }}
      

